FROM php:7.4.0-fpm-alpine

RUN apk update && apk add --no-cache \
        $PHPIZE_DEPS \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        imagemagick-dev \
        icu-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && docker-php-ext-install opcache \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && docker-php-ext-install intl

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY templates/opcache.ini $PHP_INI_DIR/conf.d/

ENV APP_ENV=prod
ENV APP_SECRET=vB43u%#@VjVTadSDF534ASQfvdsvS7dcebGn%#$453ASDF
ENV DB_HOST=10.39.64.3
ENV DB_DATABASE=comandaclub
ENV DB_USER=root
ENV DB_PASSWORD=3ygFGiCjLu1ddp5r
ENV DATABASE_URL=mysql://$DB_USER:$DB_PASSWORD@$DB_HOST:3306/$DB_DATABASE
ENV REDIS_HOST=10.0.0.3
