version: "3.7"

services:
    database:
        image: mysql:8.0.32
        container_name: "database"
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: lea
        networks:
            - lea-network
    cache:
        build: ./docker/redis
        container_name: "cache"
        ports:
            - "6379:6379"
        networks:
            - lea-network
networks:
    lea-network:
        name: lea-network
        driver: bridge
