FROM nginx:1.17.6-alpine

RUN rm -Rf /etc/nginx/config.d/*

# PRODUCTION
COPY templates/default-prod.conf /etc/nginx/conf.d/default.conf

RUN mkdir /etc/nginx/ssl

COPY files/prod-comandaclub.chained.crt /etc/nginx/ssl/comandaclub.chained.crt

COPY files/prod-comandaclub.key /etc/nginx/ssl/comandaclub.key
